"""Provider adapter registrations (26 total)."""
import llm_mcp.gateway.adapters.ollama
import llm_mcp.gateway.adapters.openai
import llm_mcp.gateway.adapters.anthropic
import llm_mcp.gateway.adapters.deepseek
import llm_mcp.gateway.adapters.gemini
import llm_mcp.gateway.adapters.groq
import llm_mcp.gateway.adapters.xai
import llm_mcp.gateway.adapters.lmstudio
import llm_mcp.gateway.adapters.vllm
import llm_mcp.gateway.adapters.openrouter
import llm_mcp.gateway.adapters.together
import llm_mcp.gateway.adapters.fireworks
import llm_mcp.gateway.adapters.perplexity
import llm_mcp.gateway.adapters.mistral
import llm_mcp.gateway.adapters.deepinfra
import llm_mcp.gateway.adapters.hyperbolic
import llm_mcp.gateway.adapters.novita
import llm_mcp.gateway.adapters.featherless
import llm_mcp.gateway.adapters.nebius
import llm_mcp.gateway.adapters.siliconflow
import llm_mcp.gateway.adapters.lepton
import llm_mcp.gateway.adapters.anyscale
import llm_mcp.gateway.adapters.replicate
import llm_mcp.gateway.adapters.sambanova
import llm_mcp.gateway.adapters.azure
import llm_mcp.gateway.adapters.bedrock
import llm_mcp.gateway.adapters.modal
import llm_mcp.gateway.adapters.cohere
